# Generated by Django 3.2.1 on 2021-05-17 17:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_slug', models.CharField(default=1, max_length=200)),
                ('title', models.CharField(max_length=264)),
                ('description', models.TextField(max_length=500)),
                ('thumbnail', models.ImageField(blank=True, upload_to='')),
                ('allowed_memberships', models.ManyToManyField(to='memberships.Membership')),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lesson_title', models.CharField(max_length=264)),
                ('video_url', models.FileField(blank=True, upload_to='images/')),
                ('tutorial_published', models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 17, 22, 50, 41, 350192), verbose_name='date published')),
                ('position', models.IntegerField()),
                ('Lesson_slug', models.CharField(default=1, max_length=200)),
                ('subject', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='courses.subject', verbose_name='Subject')),
            ],
        ),
    ]
