# Generated by Django 3.2.1 on 2021-05-17 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_lesson_tutorial_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='tutorial_published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 17, 22, 51, 27, 33669), verbose_name='date published'),
        ),
    ]
